### ISSUE TITLE
Просьба проверить домашнее задание

### ISSUE THREAD

**Issue by FFKL** [FFKL/typing-practice#1]
@JSMonk Боюсь, что я больше кода поменял, чем надо. Порезолвил варнинги и ошибки. Извиняюсь, если из-за этого сложнее проверять.

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
Мне нравится, что Вы выделили отельный тип привилигированных пользователей.
Но:
1. У Вас нет проверки ни на правильность эмейла, ни на то, что это пустая строка (мы не зря написали [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR9) указать более точные типы).
2. Помните про парадигму `Parse, don't validate`. В [данном](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR27) куске кода Вы валидируете данные. Давайте попробуем сделать так, что бы у `PrivilegedUser` был конструктор (Вы можете его сделать, с помощью [`or` композитора](https://github.com/JSMonk/typing-practice/blob/homework-task/src/utils/or.ts), который мы делали на лекции).
3. Давайте попробуем описать [эту логику](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-096045fcc15e15c86099818c37598b123dd4e9cf6d9d265213b0f1c4b6858808R39) на уровне типов, как мы это делали на лекциях.

**Comment by FFKL** [comment]
@JSMonk Попробовал исправить
1. Сделал
2. Если правильно понял, то нужно просто использовать `or` для создания объекта без ассерта?
3. Описал, но как-то получается, что нужно передавать в функцию роль вместо объекта, иначе маппинг типов не сработает. Странно, что оно не может сопоставить `user.role`.

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
1. Давайте [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-b712f225ef9aab3eb0897f3f20d97ba6c9db26525745bd68d7fac359dc9e70cfR9) и [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-40dcdaf58e0d1fa64d3c9f0b0adbb87e24d2a266d549ae7c066974d7931784dfR9), скажем что, все же строка не является валидным паролем :)
2. Не совсем понятно, зачем нам [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-c82da909ac34734aeba7705de513113c87fca9ca429b9c77e28232336af8757cR23) `Promise.resolve`. Код же синхронный.
3. Вот [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-87607b071401968dd3729d76e42faf5a31b5d203e250f19430447a4d5c534321R4) у Вас `PrivilegedUser` живет отдельно от конструктора. Давайте попробуем сделать [подобным образом](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G9oH0AuBPADgU2gXmgGV0BbAIwHsQAKAclloEoBuaCVMVAS2GgDMAThRLVGiaAOyoArgIB20OdgDucUdAC+mgFChIMAELi0WXAWLkqdA01btOPfkJFikkmfMUroB9Vo3a2nzScsDcFAoUAgA8sAA0PgkAwgB81GQAXOKCwtRgWbCMWUYaCcBZSDki+XBF0EmadXkFYngpPtAAPvWI2tD9ElKyCs21+O0IfQPTqALovdOLA+7D0GQAdFV5LFNLWsCcwAAWC0uLs-OTZ9eDHgrAm87bzLs3+4cn1NiurzcDqEchKpsC8-v0AtcIQMAgFdBF2HAokYCFFqPEfDttBgcIiBMjoAAlIbyAAqpmi2OwFD4uIMKWYQA).
4. Посмотрите на задание конфигурацию как [здесь](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgJRAGzjA3jAQQBEBZASQDkYAaGEgeSIFE0CAVetWgYQBkymFNjAC+AKFCRYCFDHoAHOACcAhlACW4PDACqABSLsmAfQ7G+AoTV0Gjp+sYbNWHLjcNsTZ4uSrixUACeioQAJsjqYDAAvNpKWHAAXOgJAHQ+lKIA3AHBONyY6giwsfjx2MkY2KkWgsIiOUEhJCChymogSjFxCZVpTizsnNliuSE6EMrdBOGRMAA+MAVFYLCLLW2qUJ2NeTB6SuoAburYAOZwoRNTsTMRUeut7dtKOWIA9O8wgDgggHwggGwggF4QX4wQCiIIABEEADCCAwAcIIAhEEAMiAwQBcIJDkTBfnDACwggFYQQDcIAjAYBhEEAciAo36AwAiIDDAMwgRKhgDEQGFkwBMICi0b9ADwgAFo4SDKZDAJwgeJxEnA0EIADUCGReAQAEK8Ez0PSDNhkegUADK3VwYhgBpgAG0qnAavw6gBdZJ6w1242m9KkSjW42W6j6+0Gk39Rhqziuo3uz1en3VWpCQOWkOiD12sNmgYuAM2mPxx0ZChRuNeh2+5xDNCBhTPTRgVL6DxeBwRtjB3N58MWyPJI0lrZliu2Tz2Rx+5NFmMiHPejPOrOphsJp2+YuKDvgLtV3tJwv13PT1euOelxeVuxmWu0dtqTv7nvecfr0OO2s7hfl8-VvsF7dDsQiGAqCAwSTQN4AGaIGAwAaFoFxQAQRwqKcKgAEbYCeYGQAAPGgACM8AAB5QAgoQ-qatBoAATNhuFgPhKTYAAfAAFIgkxKMk1xdAAZD0FToJhw6-ogShKMULHJAcxynHAFxXIxMDsWUvToKRIgAJR4J6AlQHxUQENKsoKkqxgqmqGrakawB8QJqwsak5RwJaRoMcoVkJJaOT+H+sAqN0EFQTBmDwYh86nuKtGyZxjpbsMPEhUkVFmpmoiKVkQA). Поиграйтесь немного с примером.

**Comment by FFKL** [comment]
@JSMonk Переделал

1. Изменил.
2. Дело в том, что я хочу, чтобы сообщение об ошибке обрабатывалось единообразно. И, чтобы не городить try-catch вокруг синхронного кода и повторять обработчик для вывода сообщения, решил воспользоваться `Promise.resolve`. Как-то по другому лучше сделать?
3. Вынес конструктор в тот же файл. А нормально, что идентификаторы типа и значения одинаковые? Вот eslint ругается - ` Line 7:13:  'PrivilegedUser' is already defined  @typescript-eslint/no-redeclare`
4. Посмотрел. Вынес маппинг в отдельный файл настроек, но всё равно сомнительно здесь такую типизацию добавлять, как по мне. В простом примере всё отлично выводится, но если взять ближе к нашему, но обнаруживается много неприятных мест - [Пример](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgJRAGzjA3jAQQBEBZASQDkYAaGEgeSIFE0CAVetWgYQBkymFNjAC+AKFCRYCFDHoAHOACcAhlACW4PDACqABSLsmAfQ7G+AoTV0Gjp+sYbNWHLjcNsTZ4uSriJmCoQEIQAJsjqYHhiMLEw8krqAG5qOEpwKqHgmACeMMZQOYowALwwAMo5yABGWAAUGNgAdD6UAJQA3DFx6ZnZeUpYOGWNcC2klF3+wIHBdCChymogStFx8YkpUGkZWWC5+YXFZZU19aNNTizsnJ3dsb17B4PYpehDl4zXrlNiAUEhbiYdQIWC4e4bZKpGCPfqHIrDCpVWqYBofCyCNh3daw-YDIZvC4YoS-MRHHA6CDKN4EcKRGAAHxgQJBYFgTJICyWUBWXXJMD0m3U2AA5nBQpTqWVaREohyuaoeUoumIAPSqmCAHBBAHwggDYQQC8INqYIBREEAAiCABhB9YAOEEAQiCAGRAYIAuEHNjpg2ptgBYQQCsIIBuEDt+sAwiCAORAndr9YARECtgGYQAMWwBiIFaQ4AmECdLu1gB4QAC0NqN4fNgE4QH1eiTgaCEABqBDIvAIACFeCZ6HpvmR6BRym9wesANpE-iYgC6AC41us4r2Pq0KMOYN2B9QIT2LlcXJwZ3OF2Px33LGx1wOISJN9uPiubmgZ12t7OLlP98etxPmmfXOuFNzNGAmvoPF4HMS9wfMcnzGAC30URVP2-WxPHsRwvlXC9DyAkDxl8S9FxPZo7xHbt30g8BoN-OCXzXICl1PBDz3Aj9CJ-OwzAA2h8LUKD6Ng7wJmncisNA-shBogiv3Yv94OcajDzEEQYCCGBJGgFUADNEDAYANC0MUoAIFJhRUapsBY9TIAAHjQABGeAAA9tjAUIQlGWg0AAJismy7PebAAD46kQKklBHSVVgAMm0F44BHczRFoYBECUdI2UCkdBWSYU4DFCU-JgEL8DCiKXJENpR3SKBYqiAhK2rOsG2MJsWzbcpuxiuLQUCpowoHbtfOUNqhgHUl1RgQA8EEACRArUARhBnRgQBBEHhRQAEIYEAQhAbVNANHRtWN9XNQB5EBgG0rUAfhArUAdhBzQTXbju9KaHX1L0YAtMb3XNL0bTVDVlNUoyYC6wzP1Miy4GshB3Ic9AXMBtz7KGbyuv83RMuymEhgiiyjzk2L4qgRKBSFUVxUCrLQuRsHREK8EBpxOASqUKJNO0lRdP0uBftLHy-OijGWr8u4Bv8D61M-b6qRZsBjJ0VzgZCQLaD0CXbJCZKklS9LAphvyAo55qEvVgUyYhYrSpgOmdMCJmRYgNnlE1zHArufwBsABBA9oDG0YADXU7tumB03NA6jptKbdsdbVTVNL11sNO7jq2wBxEC9a07qTbVjqTC1AEkQZ7021KMjWD00bS9XVzSaGBAHwQU0rWNbUPVtQOYCOqbzXtN1HrGtPAEUQfV9UAaRB8z2w6S5LKQZJHXEDhFuc3h+iDWPAOowDgAB3eZFkVFY6jaWgF+XmVIg3u4xBUJpkBUeQ6hAGevpKTyYAv2iwE6IA)

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
1. По поводу одинакового имени - нормально все (Мы же определяем, по-факту, type assertion для рантайма).
2. Можно немного сложнее определить тип для `getAvailableOperations`, что бы везде его красиво использовать (https://www.typescriptlang.org/play?#code/MYewdgzgLgBApmArgWxgJRAGzjA3jAQQBEBZASQDkYAaGEgeSIFE0CAVetWgYQBkymFNjAC+AKFCRYCFDHoAHOACcAhlACW4PDACqABSLsmAfQ7G+AoTV0Gjp+sYbNWHLjcNsTZ4uSriJmCoQEIQAJsjqYHhiMLEw8krqAG5qOEpwKqHgmACeMMZQOYowALwwAMo5yABGWAAUAEQE4ZENAJQA3DFx6ZnZeUpYOGUY2AB0PpRd-sCBwXQgocpqIErRcfGJKVBpGVlgufmFxWWVNfUNJIvLUKvtXRu9+4eD2KXoQ2NOLOyc02IBIIhbiYdQIWC4bqxBLJVIwJ79I5FYYVKq1TCNEFgsBQe5Q+F7RGvFGjOBjCyCNj-MTHHA6CDKd7NCJRAA+MCx4Jg7KuS1UtyUXVpMD0W3U2AA5nBQvTGWVmZFuQs+StBQCAPTqmCAHBBAHwggDYQQC8ILqYIBREEAAiCABhBDYAOEEAQiCAGRAYIAuEEtzpgurtgBYQQCsIIBuEAdhsAwiCAORAXbrDYAREBtgGYQINWwBiIDaw4AmEBdbt1gB4QAC0dpNkctgE4QP0+iTgaCEABqBDIvAIACFeCZ6HofmwyPQKOV3pCNgBtUnk-iUgC6AC51hs4gPPpMKOOYH2R9R8f3B98XJwF0uV1Pp4OKUJtyP8SJd-vPhvfmgF7294vB3Pj+e9zPxlfXNuFDdNGAxvoPC8BxDzYZdVwvcYQK-RR+V-f9bE8exHEYNst1PF8H1nUhKFvcDYjfMknwnPtv1g8B4MApCPy3DC10vFDNxvYjSLUOCALsMwQNoFiNHI9jEO8bD51oiCySg5iYNYviEKA5DnGvE8NnEEQYCCGBJGgLoaWRKsazrRtm1bFwOy7d5aRAAAzXTawbJtjBbNsTPKLSLMQMBgF4qIpSgAgUnFFRqmwHjfwgAAefE0AARngAAPHYwFCEJSVofEdGiuA4oQRLdAZNYADJtGJCcotEDC0AAJli+LsuS1LKoy6qQlFZJxTgKUZVymACvwIr0Eqs8xAAPjqRBconNLaGARAlHSHFZSUcbyraSd0igaaogIasbIM+yjPYJy+ymmbwXmsZiRHPtRuUM6hhHVSQk2vTbMMxzO3KPsdHKvsGmJBoRwutLvt+-7qVc9zPJgK7gvAUK0qqrKQnm2hPvhhKmrFSVpXm4aroW3RIsm6bZqgebFuWu9VvWmBvN8lR-MCuBocgEbcsJ465tyzoxH8TUYEABBAYDtIM7RgIN9R9GBDQlzNLUAfhBZftQBBEEAeRBw3Nc0fWdO1jQlwB2EENS1AHEQH1bQllNdV1lMrUASRBLR9TNdRjE1nV1c07R9fVLTGGBAHwQc0bVNXUvSV1WFcVy1HQ9QBGEF1KPrcARRBDUNQBpEELQWbVl72yykVT3ihyTPLqMA4AAd2VG5VjqNpaGLsuFTAKuuaAA)

Остальное - шикарно.

**Comment by FFKL** [comment]
@JSMonk Спасибо) Усложнил тип. Интересный вариант получился.

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
1. Давайте всю [логику поиска юзера](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR13) вынесем в UserService, у нас же эта логика могла бы быть на сервере, и так, будет легче поменять ее,  если вдруг у нас будет сервер 😺 
2. Залогиниться мы же можем и [под клиентом](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR18), просто ему доступ не везде будет.

**Comment by FFKL** [comment]
@JSMonk

1. Переместил логику, если я всё правильно понял.
2. Да, я тоже об этом думал, что для клиента может быть доступ на другие разделы сайта. А это не дело уже каких-то гардов роутера? Сейчас у нас эта функциональность ограничена получается.

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
Да, но вот [здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-solution#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR14) Вы запрещаете кому либо кроме админа и модератора логиниться в приложение. Данный парсинг стоит производить только там, где у нас действительно ожидается админ или модератор (например, пробрасывая аргумента в `getAvailableOperations`).

**Comment by FFKL** [comment]
@JSMonk Я это понимаю, но я же мыслю в реалиях текущей задачи) Я реакт не знаю - мне сложно понять, как правильно пользователя допускать к ресурсу. В `getAvailableOperations` решил заменить `PrivilegedUser` на `User`. Всё-таки это не его задача - знать, что кленту отсутствует доступ к дашборду. Парсинг пользователя перенёс в компонент `Dashboard`. Правильно ли я всё сделал?)

**Comment by JSMonk** [comment]
Да, довольно хорошо.
Задача принята.

**Comment by FFKL** [comment]
@JSMonk :+1: Отлично! Жду следующего!
