### ISSUE TITLE
Просьба проверить домашнее задание (контракты)

### ISSUE THREAD

**Issue by FFKL** [FFKL/typing-practice#2]
@JSMonk [Решение](https://github.com/FFKL/typing-practice/tree/homework-task-contracts)

**Comment by JSMonk** [comment]
Здравствуйте, Дмитрий.
В целом, все отлично, но есть очень неприятная проблема:
[Здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...FFKL:homework-task-contracts#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR16) Вы приводите к `User` обычный объект.
Старайтесь использовать type-guard/assert по-минимуму, так как они являются способом привести один тип к другому. Для маленьких проверок - просто вставляйте их как есть, для больших - Вам нужен подход `parse don't validate`.

**Comment by FFKL** [comment]
@JSMonk Заменил assert на простую проверку.

**Comment by JSMonk** [comment]
Супер. Задание принято 👍🏻
